### ISSUE TITLE
Make "version" clickable

### ISSUE THREAD

**Issue by zedeus** [0xpr03/nitter-status#1]
Similar to how it is on Nitter's about page, the version text should link to its commit which can easily be parsed from the same HTML element

**Comment by 0xpr03** [comment]
You mean the nitter version, not nitter-status right ?

**Comment by zedeus** [comment]
Yes, the `2023.07.28-...` versions

**Comment by 0xpr03** [comment]
What do we do for commits that aren't from your repo ? Like [nitter.cz](https://nitter.cz/)
