### ISSUE TITLE
Show whether the version is latest commit in master

### ISSUE THREAD

**Issue by zedeus** [0xpr03/nitter-status#2]
An extra "Latest commit" or similar column with a checkmark showing whether the instance is running the latest commit from master

**Comment by 0xpr03** [comment]
That would be pretty redundant as a column. My idea would be to just fetch the latest version, and then somehow mark instances if they're outdated. (The fetched latest version could be displayed in about). Maybe make the background green if it's outdated, or add a checkbox ?

**Comment by zedeus** [comment]
Good idea, using color instead of cramming in more columns is definitely the way to go
