### ISSUE TITLE
http/2 ignored

### ISSUE THREAD

**Issue by animegrafmays** [0xpr03/nitter-status#4]
over the last several days, we have worked together to identify ways to limit scraping on nitter instances. one of which is to prevent http/1.0 and http/1.1 access to nitter.poast.org. because your status page does not honor the upgrade offered by the webserver, it's returned as offline but it's very much online, just refusing http/1.0 and http/1.1 connections

**Comment by 0xpr03** [comment]
I've debugged this a little bit. I'm currently not sure what the error is exactly.
Your host seems to reset the connection right now, before any redirect is even started.
You can ping me on matrix in the nitter channel.

**Comment by 0xpr03** [comment]
Seems to work now ? Not sure what you changed. I also can't reproduce my earlier connection resets anymore.

**Comment by animegrafmays** [comment]
I turned off filtering for http/1 and http/1.1 because it's Thanksgiving weekend here. the issue still persists and i would like to troubleshoot with you but the homeserver the nitter chat is on blocks my homeserver (matrix.poast.org)

email is probably the best way to troubleshoot since federated services result in blanket bans for no reason -- if you have time Monday graf@poast.org
